version: '3.8'
services:
  mysql:
    image:  mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moviesdb
      MYSQL_USER: surya
      MYSQL_PASSWORD: surya123
      ports:
        -"3306:3306"
      networks:
        -app-network
      volumes:
        -mysql-data:/var/lib/mysql

  springboot:
    image: moviescodechef-latest.v1
    container_name: springboot-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/moviesdb
      SPRING_DATASOURCE_USERNAME: surya
      SPRING_DATASOURCE_PASSWORD: surya123
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network
networks:
  app-network:
volumes:
  mysql-data:

